# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

site.certificates_title: Certifications

# Personal info
name: Dillon Camp
title: Data Scientist and Cybersecurity Engineer
email: 
phone: 
website: https://www.dilloncamp.com
year: 2019

#SEO
description: Dillon Camp's website and resume. Dillon is a Data Scientist and Cybersecurity engineer at T-Mobile.

# Social links
twitter_username: 
github_username:  dilloncamp
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: dillon-camp
xing_username: 
pinterest_username: 
youtube_username: 
googleplus_username: 

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/screenshot.png
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
    - Lists
    - Tables
    - Links
    - Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
#more_content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: false
footer_show_email: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

#Sitemap
url: "https://dilloncamp.com"

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
